plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace "com.endoscopio.usb"
    compileSdk 34

    defaultConfig {
        applicationId "com.endoscopio.usb"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    // USB camera library (UVC protocol support)
    implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.3.3'
}
